[package]
name = "url-short"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
nanoid = "0.4"  # For generating unique IDs